name: Build Example
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
      
      - name: Setup Node.js environment
        run: npm install

      - name: Build the code
        run: npm install && npm run zip --if-present

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the code
        run: npm test --coverage

  create-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Better Test Reports Action
        uses: mridang/action-test-reporter@v1.7.0